### ISSUE TITLE
Function fileversioninfo::get-product-version should return string, not Version.

### ISSUE THREAD

**Issue by JoshMcCullough** [nant/nant#138]
If `fileversioninfo::get-product-version(fileVersionInfo)` does what I think it does - return the value set by the `AssemblyInformationalVersion` attribute, it should return a `string` - not a `Version` instance. You can use the `AssemblyInformationalVersion` attribute to set a non-version-number supporting value on the assembly. I'd like to get this value back using Nant but it is upset because my value is not a version, but a plain string.

Version 0.92.4543.0

**Comment by JoshMcCullough** [comment]
Looking at the code, I think I'm wrong about the intent of this function. But I'd still like to know how to access this highlighted property:

![image](https://cloud.githubusercontent.com/assets/4859660/6006121/09913fca-aade-11e4-8277-a7b0c9522964.png)

**Comment by rmboggs** [comment]
Sorry, I'm having a little difficulty translating your original post.  Are you saying NAnt is erroring out with the `fileversioninfo::get-product-version(fileVersionInfo)` if the assembly's product version value contains strings rather than ints?

**Comment by JoshMcCullough** [comment]
Yes. But I believe I was mistaken regarding the purpose of the function. I have forked and commited this commit (2f199556b42c4639750f4547f7f822ff5e853445) to solve my issues.

**Comment by rmboggs** [comment]
Actually, I think you were correct.  `fileversioninfo::get-product-version(fileVersionInfo)` does retrieve the Product Version you are referring to but there seems to be some odd behavior.

First off, in order to get what you are after, you need to do something like this:
```xml
<project>
  <echo message="Product Version: ${version::to-string(fileversioninfo::get-product-version(fileversioninfo::get-version-info('path/to/file.dll')))}"/>
</project>
```
I agree that it is unfortunately wordy but it pulls the version details that you are after as a string. 

But I noticed during my tests that the `FileVersionInfo` object does not deal with alpha numeric characters well in the product version property.  It changes them to zeros, (i.e.: version `1.2.3.4` will return `1.2.3.4` as expected but `1.not.a.number` will result in `1.0.0.0`).  That's rather unfortunate.

If I were you, I would try experimenting with pulling the [actual product version property from the FileVersionInfo object](https://msdn.microsoft.com/en-us/library/system.diagnostics.fileversioninfo.productversion(v=vs.110).aspx) in its own function rather than trying to go the long way around of reflecting the actual assembly.  I'm not sure if this property will properly interpret the alpha numerics but I think it is worth a shot before taking drastic measures.

**Comment by JoshMcCullough** [comment]
That doesn't work because the `FileVersionInfo` is not where this information is stored, it is in the assembly metadata. If you do the following in your assembly:

    [Assembly: AssemblyInformationalVersion("Textual Version Information")]

You can retrieve the value by looking in the `assembly.GetCustomAttributes()` array or `fileVersionInfo.ProductVersion`. After looking through the existing code, noticed that the `file-version-info::get-product-version` function should simply return `fileVersionInfo.ProductVersion` instead of building a new `Version` instance based on the different `ProductVersionXYZ` properties.

The commit I pushed (2f199556b42c4639750f4547f7f822ff5e853445) accomplishes this and also allows the user to grab any attribute they want. If you think the "get any attribute" option is not needed, then fine, but I'd at least like the `get-informational-version` function to make it into the code-base.

The second commit I pushed (be31c6affdc2e45e0cdc58f5cb5c2254a7cf156f) simply fixes the root issue in the `file-version-info::get-product-version` function.

Here are the results before and after applying this fix:

**Current Result**

    Test:

         [echo] File Version:       1.2.3.4
         [echo] Info. Version:      0.0.0.0

    BUILD SUCCEEDED


**Fixed Result**

    Test:

    [Test echo] File Version:       1.2.3.4
    [Test echo] Info. Version:      A Very Special Build

    BUILD SUCCEEDED

Test project attached. Let me know your thoughts.

[NAntTest.zip | uploaded via ZenHub](https://files.zenhub.io/54d02c95cd6c1db172e6e7ed)

**Comment by JoshMcCullough** [comment]
Any idea when/if this will end up in an official release?
