### ISSUE TITLE
If a property is programmatically set to null, property::exists returns true, but accessing property value fails

### ISSUE THREAD

**Issue by ikriv** [nant/nant#84]
A typical assumption of a script writer is that if property::exists is true, property value can be safely accessed. This, however, is not the case if NAnt is hosted by another program and the property is programmatically set to null. I found it the hard way :)

The solution would be to either have property::exist return false, or ${property} return an empty string instead of throwing an exception.

<b>C# host:</b>
            var project = new Project("example.build", Level.Verbose, 0);
            project.Properties.Add("null.property", null);

<b>NAnt script:</b>
        &lt;echo message="null.property value is ${null.property}" if="${property::exists('null.property')}" /&gt;

<b>Exception:</b>
NAnt.Core.BuildException: Property 'null.property' has not been set.

<b>Complete source code:</b> http://dev.ikriv.com/misc/NullProperty.zip

**Comment by rmboggs** [comment]
@ikriv, thanks for the example.

At first glance, it looks like the issue stems from the fact that the ```property::exists``` function is only checking to see that the property dictionary contains the property name.  It's not checking the value to see whether or not it is null. It would be a simple fix if this the desired behavior from the consensus. On the otherhand, it might be better to prevent the PropertyDictionary from adding properties with null values in the first place. Reading @robgilliam's statement makes me think that the latter would be the better solution.

@robgilliam, do you have a good example of the ```foreach``` behavior that you described previously?

**Comment by robgilliam** [comment]
@rmboggs I'm not near a computer right now, so can I direct you to the following example I wrote on Stack Overflow? http://stackoverflow.com/questions/27152977/what-does-it-mean-for-a-property-to-exist-in-nant

**Comment by rmboggs** [comment]
Yeah, looks the same.

I could add another is null type check to the function but I would like to hear from others first to make sure that this would be the correct path to fixing this.

**Comment by rmboggs** [comment]
I thought about it some more. To me: when I think about a dictionary type class and the associated contains type method, it is just checking to see whether or not that particular key exists.  It is not doing anything with the associated value. Therefore, I think that it is best to keep that function as it is.

That being said, I do think that there is value of adding a new function to perform the task that you need. Something like ```property::is-null-or-empty('property-name')``` would make sense.  Thoughts?

**Comment by rmboggs** [comment]
Ehh, disregard my previous statement.  For some reason, the name "Contains" got in my head instead of exists.  Sorry for the noise.

**Comment by JamesThorpe** [comment]
To me, this issue revolves around the question *Should nant allow the value of a property to be null?*

There are two areas here.  The first is the end user.  End users (ie those writing nant scripts) cannot set properties to null, only to blank strings.  I believe you are also unable to remove a property.

The second area is the programmatic area, such as the `foreach` and `if` tasks being discussed, but could easily extend to other 3rd party contrib dlls etc.  They are able to (currently) set properties to anything they like, including `null`.

Given both these circumstances, there are two routes that could be taken.  The first would be to extend the API available to tasks and not allow them to set properties directly, thus preventing them being able to set it to `null`.  I suspect this would be a major breaking change however.  So the simpler option is to add a nullability check to `property::exists`, and assume that `null` properties are indeed properties that, as far as nant is concerned, do not exist.  Perhaps there is a suitable place in the code where the properties collection could be periodically checked (after each task?) and `null` properties removed, so other code that would otherwise assume a property set to `null` exists works as expected.

**Comment by rmboggs** [comment]
@JamesThorpe, thank you for your input. :)

I don't think the first route you mentioned sounds feasible just because there are too many different tasks that handle properties differently. I also don't think silently dropping ```null``` value properties is a good idea either as it may cause confusion to the user.  

IMHO, there are 3 options that would address this situation:

__1 - Modify the ```property::exists``` function__
This would be a simple fix to something like this:
```csharp
[Function("exists")]
public bool Exists(string name) {
    return Project.Properties.Contains(name) 
        && Project.Properties[name] != null;
}
```
It's a simple/easy fix which I was testing last night without issues.  The only problem I see is if someone is actually using this function for only checking the existing of the property while not caring about its value and returning a false negative.

__2 - Modify the PropertyDictionary to prevent ```null``` values from being added__
This sort of fix wouldn't be too difficult because it would just require an additional check on the OnSet method and erroring out.  However, I feel that this approach would be more disruptive to the end user due because of the added error message.

__3 - Create a new function to specifically check for ```null``` property values__
This fix would be pretty simple to do and least intrusive to the users who are used to the existing behavior.  The only downside I see would be for the group of users who need to change their scripts to account for the new function.

So what do you guys think would be the appropriate solution?

Thanks,
Ryan

**Comment by JamesThorpe** [comment]
I think the best fix is option 2.  End users can't create `null` properties, so why should code be able to?

I realise it will require updates elsewhere, such as in the `foreach` task @robgilliam found and discussed on Stack Overflow, but I believe it's the best long term fix.

Failing that, go for option 1 as it does fix the issue at hand - though it does mean that code may potentially see a property as existing, even though in end user land it doesn't.

I don't like option 3, as end users don't have the concept of `null` properties as discussed, so won't necessarily know that they need to check for it.

**Comment by rmboggs** [comment]
Looking at the code for (PropertyDictionary)[https://github.com/nant/nant/blob/master/src/NAnt.Core/PropertyDictionary.cs] now and I couldn't help but laugh a bit. Line 520 of that file has the following code:

```csharp
 private static void ValidatePropertyValue(object value, Location location) {
    if (value != null) {
        if (!(value is string)) {
            throw new ArgumentException(string.Format(CultureInfo.InvariantCulture,
                ResourceUtils.GetString("NA1066"), value.GetType()),
                "value");
        }
    } else {
        // TODO: verify this
        // throw new ArgumentException("Property value '" + propertyName + "' must not be null", "value");
        return;
    }
}
```
The code is already there to error out with a null value property but it's been deactivated for some reason. Most likely before my time here but I need to dig through the commits to see why this is.

Now that I have seen this, I think my second option is the best. Barring a perfectly good reason in the commit logs as to why this was commented out in the first place.  I'll let you know what I find.

**Comment by rmboggs** [comment]
Pull request #134 should take care of this once it has been reviewed and ok'd.  Feel free to take a look as well. Any user input is welcome.

**Comment by JamesThorpe** [comment]
Looks good.  Added a note about a comment in the loop task, but the changes themselves look fine

**Comment by rmboggs** [comment]
@jamesthorpe , thanks for taking a look at the request. I appreciate that. :)

Your suggestion makes sense and I'll make the fix today sometime. I should also probably test this change with nantcontrib to make sure nothing else is broken.  I'll keep you posted.

**Comment by rmboggs** [comment]
fix committed. Thanks for reporting it,
