### ISSUE TITLE
Nant Version 0.92 escape ${}

### ISSUE THREAD

**Issue by newbie432** [nant/nant#99]
I'm having a hard time getting Nant to ignore ${xyz}. I know ${} is treated as a variable in nant, but how do i ignore since nlog config values also use the same format for variables.

Here are the options i tried:

$${xyz} produces => $${xyz}

${'${xyz}'} => Error, still treats the inner as variable

**Comment by rmboggs** [comment]
This has been fixed.  Thanks for the report.

**Comment by jbrestan** [comment]
Not sure whether I should create a new item or a comment here is enough, but in current Nightly build (0.93.5792.0) this works only if the $${}-escaped property is before all other expanded properties. Otherwise the escaped property gets expanded again, as with the ${'${}'} escaping in the original issue.
